### PR TITLE
Add peer dependency `react`

### PR DESCRIPTION
**Pull request by unindented**
The `component.js` file is requiring `react`, but it's not declared anywhere in the project as a dependency.

### CODE REVIEW

**Comment by JAStanton** [comment]
I'm curious about this. I use this package in my react-native project and I like that you don't require `react`  . I use this package like so: https://github.com/este/este/blob/master/native/src/components/component.react.js

**Comment by evocateur** [comment]
You really [shouldn't use peerDependencies](https://github.com/npm/npm/issues/5080#issuecomment-40545599). Is it really that hard to remember you need to be using React with this package?

**Comment by unindented** [comment]
@evocateur it's not about remembering, it's about correctly declaring the dependencies for this project so that tools can reason about it.

**Comment by evocateur** [comment]
Then it should be added to `dependencies`, since you accurately pointed out that it is indeed being required by a module in this package.

**Comment by unindented** [comment]
@evocateur Agreed.

**Comment by gaearon** [comment]
I will merge this after the next version of React Native comes out that uses `react` (0.14) package.
We don't want to force RN users to install `react`, this will cause other issues.

**Comment by unindented** [comment]
@gaearon Your wishes have come true.

**Comment by gaearon** [comment]
I decided to deprecate this project, as there are better maintained options now:
https://github.com/gaearon/react-pure-render#no-maintenance-intended

Thank you for sending the PR, and sorry for the trouble!

**Pull request closed without merging**
